### ISSUE TITLE
not obvious (to me) why item 57 LockingGrid needs a lock, explanation in book would save confusion for learners.

### ISSUE THREAD

**Issue by gregorianrants** [bslatkin/effectivepython#120]
forgive my likely misunderstanding, i have only just started learning about threads.

It seems to me that 

```python
class LockingGrid(Grid):
    def __init__(self, height, width):
        super().__init__(height, width)
        self.lock = Lock()

    def __str__(self):
        with self.lock:
            return super().__str__()

    def get(self, y, x):
        with self.lock:
            return super().get(y, x)

    def set(self, y, x, state):
        with self.lock:
            return super().set(y, x, state)

```

does not need a lock.  

The grid that is written to and the grid that is read from are not the same grid and as far as i can see a write and read operation on a grid item would not happen at the same time and would therefore not be subject to race conditions.

Is this an example of defensive programming? Where it is good practice to define a lock for something that is readable and writable and will be used in a thread, even if the way it is intially used is not subject to race conditions. because it may be used differently in the future and the future use may be subect to race conditions.  Clarification would help as it has left me doubting that i understand the fundamental reason why we need locks and other learners may have the same confusion.

thanks for an excelllent book.

**Comment by bslatkin** [comment]
The issue is that multiple threads are accessing the underlying data structure at the same time. Sometimes this is okay for reads, often it's not okay for writes. Item 54 ("Use Lock to Prevent Data Races in Threads") has some more background information about why this is important. I agree that it's defensive programming and not strictly necessary. Depending on the situation you might be able to make different trade-offs. In this case, it's mostly trying to demonstrate what might be possible when accessing a shared resource concurrently. Please reopen if that doesn't clear it up!

Thanks for reading!

**Comment by gregorianrants** [comment]
Yes that clears it up for me. Thank you very much for your response it is much appreciated.
