### ISSUE TITLE
Classes in improper order

### ISSUE THREAD

**Issue by jodyhart** [bslatkin/effectivepython#21]
Using Python 2 (which forced me to change the metaclass=Meta argument into the statement __metaclass__=Meta, though I don't think it should matter), I found that the example would not run with the classes defined in the given order: Meta, DatabaseRow, Field, BetterCustomer, because when class DatabaseRow is first executed, it invokes Meta.__new__(), which compares the type of an object against type 'Field', and Field has not yet been defined.  If, however, I switch the positions of classes DatabaseRow and Field, then everything works.

**Comment by jodyhart** [comment]
I forgot to mention that I was referring to the example on page 114.

**Comment by bslatkin** [comment]
I think I see what you're saying. I agree that the `Field` class must be defined first. In the book, first I define `Field`, then a redefine it without any parameters in the constructor. You can see that here:

https://github.com/bslatkin/effectivepython/blob/master/example_code/item_35.py

But this means the `Field` class used by `Meta` when defining `DatabaseRow` is technically the wrong version of `Field`. The code works because the other `Field` class was defined earlier. And then `BetterCustomer` isn't defined until *after* the correct `Field` class is defined, overriding the old one.

I'd file this problem under "artistic license" because I think when it's presented this way it flows more logically to the reader. My intention was the reader would go back up to the original definition of `Field` and edit its definition to have the new behavior of not having to accept any constructor parameters. That's why I say:

> To work with the metaclass, the field descriptor is largely unchanged. The only difference is that it no longer requires any arguments to be passed to its constructor. Instead, its attributes are set by the Meta.__new__ method above.

One way to clarify this is to say "The only *change required* is that..."

**Comment by bslatkin** [comment]
Also: Thanks for the report!

**Comment by jodyhart** [comment]
Hi Brett –

I appreciate your reply and will study it.

Jody Hart

**Comment by bslatkin** [comment]
Going to leave this as-is.
