### ISSUE TITLE
not actually a generator

### ISSUE THREAD

**Issue by tellspec-mark** [bslatkin/effectivepython#22]
in item 9, the example of composing generators,
roots = ((x, x**0.5) for x in it)
is actually just one generator returning tuples.

**Comment by bslatkin** [comment]
I'm not sure I understand what you mean? Could you elaborate a bit?

Here's the full example. First, my_file.txt contains:

```
100
57
15
1
12
75
5
86
89
11
```

Then I create two generators, one dependent on the other:

```python
it = (len(x) for x in open('/tmp/my_file.txt'))
roots = ((x, x**0.5) for x in it)
```

Then if you progress the second iterator, it progresses the first iterator, yielding a result value:

```python
print(next(roots))
```

With the output:

```
(15, 3.872983346207417)
```

The generators are *composed* because calling `next` on one will cause `next` to be called on the other one automatically.

**Comment by tellspec-mark** [comment]
oh, sorry, i hadn't realized that 'it' was another generator.
