### ISSUE TITLE
Item 25: Doesn't seem accurate to say "calls"

### ISSUE THREAD

**Issue by bslatkin** [bslatkin/effectivepython#41]
Originally reported in #40:

> On a closely related note, in the paragraph after the last block of code on p. 72, it doesn't seem accurate to say that TimesFiveCorrect.__init__ calls PlusTwoCorrect.__init__; that's just the order in which those initializers are run.

**Comment by bslatkin** [comment]
The text in question is:

> When I call GoodWay(5), it in turn calls TimesFiveCorrect.__init__, which calls PlusTwoCorrect.__init__, which calls MyBaseClass.__init__. Once this reaches the top of the diamond, then all of the initialization methods actually do their work in the opposite order from how their __init__ functions were called. MyBaseClass.__init__ assigns the value to 5. PlusTwoCorrect.__init__ adds 2 to make value equal 7. TimesFiveCorrect.__init__ multiplies it by 5 to make value equal 35.

The `__init__` methods are calling `super()`. And `super()` is doing the work. If you leave out the call to `super()` you won't get the correct behavior. So I think it's accurate to say `TimesFiveCorrect.__init__` calls `PlusTwoCorrect.__init__` and so on. `super()` has some special sauce for which initializer is actually called at each step, but that is the mechanism that makes this work.

Please reopen this issue, @PeterDrake, if you disagree. Thanks for the report.

**Comment by PeterDrake** [comment]
I'm confused because you say that "`TimesFiveCorrect.__init__` ... calls `PlusTwoCorrect.__init__`". I look at the code for `TimesFiveCorrect.__init__` and think, "No it doesn't. There's a call to `super`, but I would expect that to call initializers from `TimesFiveCorrect`'s ancestors." Maybe my Java background is getting in the way, but I can't imagine that `super` calls things from siblings (or even more distant non-ancestors).

Given the discussion in #40, it sounds like the following is happening:

- `TimesFiveCorrect.__init__` wants to call (via `super`) `MyBaseClass.__init__`.
- `PlusTwoCorrect.__init__` wants to call (via `super`) `MyBaseClass.__init__`.
- `GoodWay.__init__` wants to call (via `super`) both `TimesFiveCorrect.__init__` and `PlusTwoCorrect.__init__`.

The `super` mechanism, using the complicated C3 linearization, ensures that:

- No initializer is called more than once. (Without it, `MyBaseClass.__init__` would be called twice.)
- Anything that wants to call a particular initializer is completed after that call.
- Any remaining questions about ordering of the initializer calls is resolved based on the order in which superclasses are listed. The calls *start* in left-to-right order, but *finish* in the reverse order.

In this case, `TimesFiveCorrect.__init__` starts before `PlusTwoCorrect.__init__` but is finished afterward. It is *as if* `TimesFiveCorrect.__init__` called `PlusTwoCorrect.__init__`.

Is this right?

**Comment by bslatkin** [comment]
> I can't imagine that super calls things from siblings (or even more distant non-ancestors).

It does. That is the mechanism that powers super.

Here's the example code and I've added an exception to `PlusTwoCorrect.__init__` to show the stack.

```python
class MyBaseClass(object):
    def __init__(self, value):
        self.value = value

class TimesFiveCorrect(MyBaseClass):
    def __init__(self, value):
        super(TimesFiveCorrect, self).__init__(value)
        self.value *= 5

class PlusTwoCorrect(MyBaseClass):
    def __init__(self, value):
        super(PlusTwoCorrect, self).__init__(value)
        self.value += 2
        raise Exception('Raising an exception')  # Note this exception

class GoodWay(TimesFiveCorrect, PlusTwoCorrect):
    def __init__(self, value):
        super(GoodWay, self).__init__(value)
```

When you run this you'll get:

```
$ ./item_25_example_10.py 
Traceback (most recent call last):
  File "./item_25_example_10.py", line 43, in <module>
    foo = GoodWay(5)
  File "./item_25_example_10.py", line 41, in __init__
    super(GoodWay, self).__init__(value)
  File "./item_25_example_10.py", line 30, in __init__
    super(TimesFiveCorrect, self).__init__(value)
  File "./item_25_example_10.py", line 37, in __init__
    raise Exception('Raising an exception')
```

`GoodWay()` calls `GoodWay.__init__()` calls `TimesFiveCorrect.__init__()` calls `PlusTwoCorrect.__init__()`. That example is for Python 2 because that's what we've been discussing.

You can see how this is implemented in Python 3 in the [CPython source here](https://github.com/python/cpython/blob/d899da595f1d16795c040cb03ae35dbb1b6d40d9/Objects/typeobject.c#L7251). It's traversing the MRO to get the `__init__` attribute by looking up the current object's type in the MRO, and then taking whatever type is after that.
