### ISSUE TITLE
More informative Errata

### ISSUE THREAD

**Issue by gsaponaro** [bslatkin/effectivepython#44]
Hey, thanks for the great book.

It would be helpful if we had more granular Errata information compared to the [current page](https://github.com/bslatkin/effectivepython/blob/master/Errata.md). Something on a per-printing basis like for [this book](http://www.aristeia.com/BookErrata/ec++3e-errata.html).

Right now, the only information that we have is whether an issue is confirmed and if it is "Fixed for the next printing" (which printing? which date?). It would be practical to see which corrections apply if I have, say, the 2nd printing in my hands.

**Comment by bslatkin** [comment]
The hardest part on resolving this issue is that I don't have much visibility or control over the meta data that's in the per-printing info that is in the book. And when people report a problem, they often don't include the printing number or know where to look to find it. But I will investigate if I can do this better in a future release.

**Comment by bslatkin** [comment]
I did update the errata page to deep link into all confirmed issues, not just open ones, so it should be easier for someone to find an issue across all printings.
