### ISSUE TITLE
Item 17: Iter() on iterator

### ISSUE THREAD

**Issue by santhosh-kasa** [bslatkin/effectivepython#49]
Hi,

In Item 17:
_"The protocol states that when an iterator is passed to the iter built-in function, iter will return the iterator itself."_

In the corresponding code:
`if iter(numbers) is iter(numbers):`

shouldn't it be:
`if iter(numbers) is numbers:`

Sorry if I am missing anything.

-Santhosh Kasa.

Slatkin, Brett. Effective Python: 59 Specific Ways to Write Better Python (Effective Software Development Series) (Kindle Locations 1714-1715). Pearson Education. Kindle Edition.

**Comment by ivytin** [comment]
Both `if iter(numbers) is iter(numbers)` and `if iter(numbers) is numbers` are correct. `is` will return `True` if two variables point to the same object, and two new iterators can not be the same object.

**Comment by bslatkin** [comment]
@santhosh-kasa Both `iter(numbers) is numbers` and `iter(numbers) is iter(numbers)` evaluate to the same thing. That means you understand the iterator protocol. Congrats! I use the second form because it emphasizes how the iterator protocol works.

@ivytin That's incorrect. You should [read about the iterator protocol here](https://docs.python.org/3/library/stdtypes.html#iterator-types). Specifically "iterator.__iter__(): Return the iterator object itself..."
