### ISSUE TITLE
Item 17 - normalize_defensive

### ISSUE THREAD

**Issue by romankleiner** [bslatkin/effectivepython#6]
In the normalize_defensive() function, page 42, would it be more natural to use

"if numbers is iter(numbers)"

rather than 

"if iter(numbers) is iter(numbers)" ?

Both are correct, but the former looks a bit clearer.

**Comment by bslatkin** [comment]
Thanks for the report! You're correct that the second call to `iter` isn't required. If you understand this, then you also understand the iterator protocol and that's great. I think this is less obvious to new readers of the code. By explicit using `iter` twice I think it's more clear to new readers of the code _why_ this is a problem: iterating twice will break because it's actually just a single iteration. I should add a note to make this clear, though.

**Comment by romankleiner** [comment]
Thank you for the response - makes sense.

Enjoying the book by the way - you filled in an important gap.

Much appreciated,
   Roman.

**Comment by romankleiner** [comment]
I have a few more comments - please let me know if you prefer them in a separate ticket (or if you consider them wrong, which is perfectly fine)

1. In Item 17, `ReadVisits` object, one point of caution is exhaution of file handles. Each invocation of __iter__ creates a new file handle, and since it is implicit and hidden in many situations (e.g. `for value in numbers`), this side effect is hidden from the caller. Of course, if generators are created in situations where sequence re-generation does not consume OS resources, this is less relevant.

2. In several places in the book, it is mentioned that loading large sequences/lists in their entirety can cause a crash. Many modern Python users use 64-bit runtime, so they are more likely to go into swap long before crash can become an issue. It's of course entirely a matter of taste, but maybe it's possible to say `crash or swap`?

3. Item 19, p.47: "extend a function's parameters" -> "extend function's parameters"

**Comment by bslatkin** [comment]
Here's fine for these reports.

1. I agree in general. In this example, the file handles will be cleaned up because the generator is exited. In other cases where it's not, the GC will eventually addresses that. I agree that realizing you're using file handles like this is important. However, my goal was to keep each item in the book as short as possible. I had to leave out a lot of nuances like this.

1. It really depends on your operating system. If you have a ulimit set or are running Python in any kind of container, you'll see this `MemoryError` behavior. That's what I mean by crash. Swap is more specific and more correct, but I think it can be confusing to readers who aren't necessarily well-versed in operating systems topics.

1. Do you mean this sentence:  
    > The third reason to use keyword arguments is that they provide a powerful way to extend a function’s parameters while remaining backwards compatible with existing callers.  

    I think this is correct as is. Another way to say it would be "extend function parameters".


Please reopen this issue if you have any more! Thanks again for your comments and questions.

**Comment by romankleiner** [comment]
Ok, thanks. I understand the reasoning behind the first two points. As for the third one (which is purely grammatical), it seemed to me that "a" refers to "parameters", but it is actually referring to "function", which as you say, is correct.
Sure, will reopen if any other comments occur to me or the guys in the team - I am on my second round.

Thanks for your time in answering this,
   Roman.
